apiVersion: v1
kind: Template
metadata:
  name: tomcat-velloso
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${APPLICATION_NAME}:latest
    source:
      git:
        uri: ${APLICATION_REPOSITORY_GIT}
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: tomcat7alpineos:latest
          namespace: openshift
      type: Source
    triggers:
    - type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: The web server's http port.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentConfig: ${APPLICATION_NAME}
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    replicas: 1
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: ${APPLICATION_NAME}
          deploymentConfig: ${APPLICATION_NAME}
        name: ${APPLICATION_NAME}
      spec:
        containers:
        - env:
          image: ${APPLICATION_NAME}
          imagePullPolicy: Always
          name: ${APPLICATION_NAME}
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${APPLICATION_NAME}
        from:
          kind: ImageStreamTag
          name: ${APPLICATION_NAME}:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  id: ${APPLICATION_NAME}-http
  kind: Route
  metadata:
    annotations:
      description: Route for application's http service.
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}
  spec:
    host: ${HOSTNAME_HTTP}
    to:
      name: ${APPLICATION_NAME}
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: database
    name: database
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: database
    name: database
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: database:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${DATABASE_REPOSITORY_GIT}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: oracle-xe-11g:latest
          namespace: openshift
      type: Docker
    triggers:
    - type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      application: database
    name: database
  spec:
    replicas: 1
    selector:
      deploymentConfig: database
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          application: database
          deploymentConfig: database
        name: database
      spec:
        containers:
        - env:
          image: database
          imagePullPolicy: Always
          name: database
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 1521
            protocol: TCP
          - containerPort: 22
            protocol: TCP
          securityContext:
            privileged: true
        serviceAccount: velloso
        serviceAccountName: velloso
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - database
        from:
          kind: ImageStreamTag
          name: database:latest
      type: ImageChange
    - type: ConfigChange
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: velloso
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      description: Expoe uma porta de acesso ao Banco de Dados
    name: database
  spec:
    ports:
    - name: oracle
      port: 1521
      targetPort: 1521
    selector:
      name: database
parameters:
- description: Nome da Aplicação
  name: APPLICATION_NAME
  required: true
  value: tomcat
- description: 'Nome da Rota. Se deixar em branco, será <nome-da-aplicacao>-<projeto>.<dominio>'
  name: HOSTNAME_HTTP
- description: 'Endereço do Repositório GIT onde se encontra a aplicação WAR'
  displayName: Repositório GIT da aplicação
  name: APLICATION_REPOSITORY_GIT
  required: true
  value: http://gogs.cloudapps.example.com/gogs/aplicacao.git
- description: 'Endereço do Repositório GIT onde se encontra os dados'
  displayName: Repositório GIT da Base de Dados 
  name: DATABASE_REPOSITORY_GIT
  required: true
  value: http://gogs.cloudapps.example.com/gogs/velloso.git
